name: Build and Release FlanYD

on:
  push:
    tags:
      - 'flanyd-v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build binaries using Docker
        run: |
          mkdir dist
          docker build -t flanyd-builder-windows -f YoutubeDownloader/Dockerfile.windows YoutubeDownloader
          docker run --rm -v ${{ github.workspace }}/dist:/app/dist flanyd-builder-windows
          docker build -t flanyd-builder-linux -f YoutubeDownloader/Dockerfile.linux YoutubeDownloader
          docker run --rm -v ${{ github.workspace }}/dist:/app/dist flanyd-builder-linux

      - name: Upload Release Artifact
        uses: softprops/action-gh-release@v1
        with:
          files:
            - dist/FlanYD.exe
            - dist/FlanYD
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
